Added the app content into Vite project
RehanPaismo/myTodoApp pull request #1
Opened 2024-10-23 08:03 UTC by RehanPaismo

2024-10-23 09:47 UTC, saqlain-paismo requested changes

2024-10-23 09:47 UTC, saqlain-paismo commented on src/Components/AddToDo.jsx
> +    if (todo != ""){
always use `===` or in case of negation values use `!==`

2024-10-23 09:47 UTC, saqlain-paismo commented on src/Components/AddToDo.jsx
> +            }}
always try to create separate functions instead of writing in line

2024-10-23 09:47 UTC, saqlain-paismo commented on src/Components/AddToDo.jsx
> +  const Add = () => {
function and variable names always starts with small case

2024-10-23 09:47 UTC, saqlain-paismo commented on src/Components/TodoClass.js
> +class ToDoClass {
why do we have a component with todoClass name?

2024-10-24 07:43 UTC, RehanPaismo commented on src/Components/TodoClass.js
> +class ToDoClass {
as i started implementing MobX, so there this component is here.

2024-10-24 07:44 UTC, RehanPaismo commented on src/Components/AddToDo.jsx
> +  const Add = () => {
Ok, Understand

2024-10-24 07:46 UTC, RehanPaismo commented on src/Components/AddToDo.jsx
> +    if (todo != ""){
Understand.

2024-10-24 07:48 UTC, RehanPaismo commented on src/Components/AddToDo.jsx
> +            }}
Understand

2024-10-24 07:54 UTC, saqlain-paismo approved these changes

2024-10-24 08:29 UTC, merged